# _*_ coding:utf-8 _*_

__author__ = 'bobby'
__date__ = '2018/8/3 15:06'
class AddMerchantPage:
    #merchanttype为individu的页面布局

    brandname = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/span[1]"
    brandnameinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/span[2]/input"
    brandnametip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/em"
    email = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[2]/span[1]"
    emailinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[2]/span[2]/input"
    emailtip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[2]/em"
    contactnumber = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[1]/span[1]"
    contactnumberinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[1]/span[2]/input"
    contactnumbertip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[1]/em"
    merchanttype = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[2]/span[1]"
    merchanttypeselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[2]/span[2]/select"
    merchanttypetip = ""
    category = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[1]/span[1]"
    categoryselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[1]/span[2]/select"
    categorytip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[1]/em"
    criteria = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[2]/span[1]"
    criteriaselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[2]/span[2]/select"
    criteriatip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[2]/em"
    siup = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[1]/span[1]"
    siupinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[1]/span[2]/input"
    siuptip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[1]/em"
    province = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[2]/span[1]"
    provinceselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[2]/span[2]/select"
    provincetip = ""
    city = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[1]/span[1]"
    cityselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[1]/span[2]/select"
    citytip = ""
    district = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[2]/span[1]"
    districtinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[2]/span[2]/input"
    districttip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[2]/em"
    village = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[1]/span[1]"
    villageinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[1]/span[2]/input"
    villagetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[1]/em"
    postcode = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[2]/span[1]"
    postcodeinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[2]/span[2]/input"
    postcodetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[2]/em"
    address = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[7]/p/span[1]"
    addressinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[7]/p/span[2]/input"
    addresstip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[7]/p/em"
    photosiup = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[1]/p/span[2]"
    photosiupimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[1]/p/span[1]/input"
    photonpwpcompany = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[2]/p/span[2]"
    photonpwpcompanyimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[2]/p/span[1]/input"
    phototdp = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[3]/p/span[2]"
    phototdpimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[3]/p/span[1]/input"

    name = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[1]/span[1]"
    nameinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[1]/span[2]/input"
    nametip =  "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[1]/em"   #name没有为空的提示,bug 点击提交按钮后才会显示
    typeid = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[2]/span[1]"
    typeidselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[2]/span[2]/select"
    typeidtip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[2]/em"
    identitynumber = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[1]/span[1]"
    identitynumberinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[1]/span[2]/input"
    identitynumbertip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[1]/em"
    npwp = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[2]/span[1]"
    npwpinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[2]/span[2]/input"
    npwptip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[2]/em"
    addresstwo = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[3]/p[1]/span[1]"
    addresstwoinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[3]/p[1]/span[2]/input"
    addresstwotip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[3]/p[1]/em"   #addresstwo没有为空的提示，点击提交按钮后才会显示
    nationality = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[3]/p[2]/span[1]"
    nationalityselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[3]/p[2]/span[2]/select"
    nationalitytip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[3]/p[2]/em"
    phone = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[4]/p[1]/span[1]"
    phoneinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[4]/p[1]/span[2]/input"
    phonetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[4]/p[1]/em"   #phone没有为空的提示 点击提交按钮后才会显示
    emailtwo = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[4]/p[2]/span[1]"
    emailtwoinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[4]/p[2]/span[2]/input"
    emailtwotip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[4]/p[2]/em"   #emailtwo没有为空的提示 点击提交按钮后才会显示
    photofullfacebust = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[2]/div/p/span[2]"
    photofullfacebustimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[2]/div/p/span[1]/input"
    photofullfacebusttip = ""   #没有不为空的提示，bug ,有星号，但不填写也能提交

    locationphoto = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[1]/p/span[2]"
    locationphotoimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[1]/p/span[1]/input"
    locationphototip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[1]/em"
    photoofthecashiersdesk = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[2]/p/span[2]"
    photoofthecashiersdeskimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[2]/p/span[1]/input"
    otherphoto = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[3]/p/span[2]"
    otherphotoimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[3]/p/span[1]/input"

    bank = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[1]/span[1]"
    bankselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[1]/span[2]/select"
    banktip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[1]/em"
    accountname = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[2]/span[1]"
    accountnameinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[2]/span[2]/input"
    accountnametip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[2]/em"
    accountnumber = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[2]/p/span[1]"
    accountnumberinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[2]/p/span[2]/input"
    accountnumbertip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[2]/p/em"

    qrindoamount = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[10]/div[1]/span"
    qrindoamountinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[10]/div[1]/p/input"
    qrindoamounttip = ""
    checkbutton = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[10]/div[1]/p/a"
    checktip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[11]"

    cancelbutton = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[13]/p/span[1]/button"
    submitbutton = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[13]/p/span[2]/button"


class AddMerchantPageCompany:
    #merchanttype为Company的页面布局

    brandname = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/span[1]"
    brandnameinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/span[2]/input"
    # brandnameinput = "/html/body/div[3]/div[2]/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/span[2]/input[2]/input"   #用于错误路径调试
    brandnametip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[1]/em"
    email = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[2]/span[1]"
    emailinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[2]/span[2]/input"
    emailtip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[1]/p[2]/em"
    contactnumber = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[1]/span[1]"
    contactnumberinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[1]/span[2]/input"
    contactnumbertip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[1]/em"
    merchanttype = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[2]/span[1]"
    merchanttypeselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[2]/p[2]/span[2]/select"
    merchanttypetip = ""
    category = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[1]/span[1]"
    categoryselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[1]/span[2]/select"
    categorytip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[1]/em"
    criteria = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[2]/span[1]"
    criteriaselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[2]/span[2]/select"
    criteriatip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[3]/p[2]/em"
    siup = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[1]/span[1]"
    siupinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[1]/span[2]/input"
    siuptip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[1]/em"
    province = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[2]/span[1]"
    provinceselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[4]/p[2]/span[2]/select"
    provincetip = ""
    city = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[1]/span[1]"
    cityselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[1]/span[2]/select"
    citytip = ""
    district = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[2]/span[1]"
    districtinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[2]/span[2]/input"
    districttip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[5]/p[2]/em"
    village = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[1]/span[1]"
    villageinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[1]/span[2]/input"
    villagetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[1]/em"
    postcode = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[2]/span[1]"
    postcodeinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[2]/span[2]/input"
    postcodetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[6]/p[2]/em"
    address = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[7]/p/span[1]"
    addressinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[7]/p/span[2]/input"
    addresstip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[7]/p/em"
    company = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[1]/span[1]"
    companyinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[1]/span[2]/input"
    companytip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[1]/em"
    officialwebsite = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[2]/span[1]"
    officialwebsiteinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[2]/span[2]/input"
    officialwebsitetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[2]/em"
    npwptaxid = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[3]/span[1]"
    npwptaxidinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[3]/span[2]/input"
    npwptaxidtip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[1]/div[8]/p[3]/em"
    photosiup = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[1]/p/span[2]"
    photosiupimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[1]/p/span[1]/input"
    photonpwpcompany = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[2]/p/span[2]"
    photonpwpcompanyimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[2]/p/span[1]/input"
    phototdp = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[3]/p/span[2]"
    phototdpimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[2]/div[2]/div[3]/p/span[1]/input"

    name = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[1]/span[1]"
    nameinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[1]/span[2]/input"
    nametip =  "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[1]/em"   #name没有为空的提示,bug 点击提交按钮后才会显示
    position = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[2]/span[1]"
    positioninput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[2]/span[2]/input"
    positiontip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[1]/p[2]/em"
    phone = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[1]/span[1]"
    phoneinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[1]/span[2]/input"
    phonetip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[1]/em"   #phone没有为空的提示 点击提交按钮后才会显示
    emailtwo = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[2]/span[1]"
    emailtwoinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[2]/span[2]/input"
    emailtwotip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[1]/div[2]/p[2]/em"   #emailtwo没有为空的提示 点击提交按钮后才会显示
    photofullfacebust = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[2]/div/p/span[2]"
    photofullfacebustimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[4]/div[2]/div/p/span[1]/input"
    photofullfacebusttip = ""   #没有不为空的提示，bug ,有星号，但不填写也能提交

    locationphoto = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[1]/p/span[2]"
    locationphotoimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[1]/p/span[1]/input"
    locationphototip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[1]/em"
    photoofthecashiersdesk = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[2]/p/span[2]"
    photoofthecashiersdeskimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[2]/p/span[1]/input"
    otherphoto = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[3]/p/span[2]"
    otherphotoimage = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[6]/div/div[3]/p/span[1]/input"

    bank = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[1]/span[1]"
    bankselect = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[1]/span[2]/select"
    banktip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[1]/em"
    accountname = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[2]/span[1]"
    accountnameinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[2]/span[2]/input"
    accountnametip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[1]/p[2]/em"
    accountnumber = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[2]/p/span[1]"
    accountnumberinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[2]/p/span[2]/input"
    accountnumbertip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[8]/div[2]/p/em"

    qrindoamount = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[10]/div[1]/span"
    qrindoamountinput = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[10]/div[1]/p/input"
    qrindoamounttip = ""
    checkbutton = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[10]/div[1]/p/a"
    checktip = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[11]"

    cancelbutton = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[13]/p/span[1]/button"
    submitbutton = "/html/body/div[3]/div[2]/ui-view/ui-view/div[2]/div/form/div[13]/p/span[2]/button"

